"""empty message

Revision ID: 4089cb4bb812
Revises: de5deca152e5
Create Date: 2021-03-29 21:44:07.683015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4089cb4bb812'
down_revision = 'de5deca152e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    op.alter_column('post', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('post', 'read_count')
    op.alter_column('comment', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
