"""empty message

Revision ID: 683e44120711
Revises: 69bca1f0b6fc
Create Date: 2021-03-25 20:50:01.749532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '683e44120711'
down_revision = '69bca1f0b6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    op.drop_index('email', table_name='cms_user')
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.create_index('email', 'cms_user', ['email'], unique=True)
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
