"""empty message

Revision ID: 69bca1f0b6fc
Revises: 3646df9a3a4c
Create Date: 2021-03-25 20:33:41.825483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bca1f0b6fc'
down_revision = '3646df9a3a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'usrname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('usrname', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', 'username')
    # ### end Alembic commands ###
