"""empty message

Revision ID: 70133b59f77c
Revises: 4089cb4bb812
Create Date: 2021-03-29 21:45:44.414548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70133b59f77c'
down_revision = '4089cb4bb812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('post', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('comment', 'author_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
