"""empty message

Revision ID: 70c380ccf62f
Revises: eff5fb5e6f1c
Create Date: 2021-04-05 17:21:54.102058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c380ccf62f'
down_revision = 'eff5fb5e6f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('front_user', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'status')
    op.drop_column('cms_user', 'status')
    # ### end Alembic commands ###
